// 全站用户可见文案字典。zh / en 双语镜像。
// 设计原则：
// 1. 产品定位：AI Token 交易市场，双边受众（API 用户 + Token Provider）。
// 2. 命名统一：cc-switch Market（主品牌）+ Market（简称）。不再使用 TokenMarket。
// 3. 语气：明快、直接、不卖弄机制术语；账本/ledger/对账放二级说明。

export const BRAND = {
  zh: {
    name: "cc-switch Market",
    category: "AI Token 交易市场",
    tagline: "给 API 用户买能力，给 Token Provider 卖容量。",
    metaDescription:
      "给 API 用户买能力，给 Token Provider 卖容量。兼容 OpenAI / Anthropic 调用方式，价格公开，收益可提现。",
    pageTitle: "cc-switch Market · AI Token 交易市场",
  },
  en: {
    name: "cc-switch Market",
    category: "An AI token marketplace",
    tagline: "Buy capability as an API user. Sell capacity as a token provider.",
    metaDescription:
      "An AI token marketplace. OpenAI / Anthropic compatible, transparent pricing, payout-ready earnings.",
    pageTitle: "cc-switch Market · AI Token Marketplace",
  },
} as const;

export const copy = {
  zh: {
    nav: {
      home: "首页",
      dashboard: "控制台",
      claim: "收益",
      support: "工单",
      board: "看板",
      admin: "管理",
      announcements: "系统公告",
      menu: "菜单",
    },
    auth: {
      login: "邮箱登录",
      logout: "退出",
      checking: "校验中",
      admin: "管理员",
      loginTitle: "邮箱登录",
      loginDescEmail: "输入邮箱，6 位验证码会发到你邮箱。",
      loginDescCode: "输入收到的 6 位码。",
      email: "邮箱",
      code: "6 位验证码",
      sendCode: "发送验证码",
      verifyLogin: "登录",
      changeEmail: "换个邮箱",
      loginSuccess: "登录成功",
      turnstileRequired: "请先完成人机验证。",
      turnstileFailed: "人机验证加载失败，请刷新后重试。",
    },
    common: {
      themeLight: "浅色",
      themeDark: "深色",
      language: "语言",
      chinese: "中文",
      english: "English",
      close: "关闭",
    },
    landing: {
      heroBadge: "平台抽成 · 公开价格 · 30 秒上手",
      heroBrand: "cc-switch Market",
      heroH1Prefix: "AI Token",
      heroH1Highlight: "交易市场",
      heroSubtitle:
        "给 API 用户买能力，给 Token Provider 卖容量。兼容 OpenAI / Anthropic 调用方式，价格公开，收益可提现。",
      heroPricePromise: "任何模型，Market 调用价都是官方参考价的 1/10。",
      heroCtaPrimary: "打开控制台",
      heroCtaSecondary: "我是 Provider",
      heroPricingLink: "查看价格 →",
      metrics: [
        { label: "任意模型", value: "官方价 1/10" },
        { label: "价格公开", value: "透明结算" },
        { label: "收益可提", value: "Gate.io · 工单兜底" },
      ],
      flowTitle: "从 API 请求到 Provider 收益",
      flowSubtitle:
        "用户调用 → market 路由计费 → Provider 收到对应收益。每一笔可按 request id 对账。",
      flowSteps: [
        { label: "API 用户", note: "Authorization: sk-cs-…" },
        { label: "Market", note: "预授权 / 计费" },
        { label: "Router", note: "注入 X-Share-Token" },
        { label: "cc-switch", note: "本地代理" },
        { label: "上游", note: "OpenAI · Anthropic" },
      ],
      flowStepBadge: (i: number) => `第 ${i} 站`,
      featuresTitle: "为什么用这个 Market",
      features: [
        {
          title: "每一笔都进账本",
          body: "充值、消费、提现、退款，都查得到、对得上。",
        },
        {
          title: "平台抽成公开",
          body: "用户花费、平台抽成、Provider 净收入都按账本公开记录。",
        },
        {
          title: "边推边算清",
          body: "SSE 边转发边解析 usage，按真实 token 结算，不估算。",
        },
        {
          title: "先锁一点，再花",
          body: "请求前小额预授权。超支不卡你，欠账不坑 Provider。",
        },
        {
          title: "改一行 URL，跑",
          body: "OpenAI / Anthropic / Gemini SDK 都认这个 base_url。",
        },
        {
          title: "走不通？人来兜",
          body: "Gate.io 自动优先；卡了开工单，人工打款。",
        },
      ],
      pricingTitle: "公开价格",
      pricingSubtitle: "Market 调用价按官方参考价 1/10 展示，平台抽成按 Market + Router 总抽成展示。",
      pricingBadge: "平台抽成",
      pricingCol: {
        model: "模型",
        input: "输入 / 1M",
        output: "输出 / 1M",
        cacheRead: "缓存读 / 1M",
        cacheWrite: "缓存写 / 1M",
        inputShort: "输入",
        outputShort: "输出",
        cacheReadShort: "缓存读",
        cacheWriteShort: "缓存写",
      },
      pricingEmpty: {
        title: "暂无价格",
        body: "管理员设置好统一 token 价格后将在这里展示。",
      },
      pricingProviderEmpty: {
        title: (provider: string) => `暂无 ${provider} 价格`,
        body: "管理员设置后将在此 tab 展示。",
      },
      pricingFooter:
        "删除线为官方参考价，粗体为 Market 当前价。空白格表示官方未单独公开该项；未在首页列出的模型仍按后台兜底规则计费。",
      pricingPageInfo: (current: number, total: number, count: number) =>
        `第 ${current} / ${total} 页 · 共 ${count} 条`,
      pricingPrev: "上一页",
      pricingNext: "下一页",
      howToTitle: "两边都简单",
      howToSubtitle: "用户接入和 Provider 上架，各 3-4 步搞定。",
      howToApi: {
        title: "我是 API 用户",
        steps: [
          { title: "登录并充值", body: "邮箱验证码登录，Dodo Payments 单次充值。" },
          { title: "创建 API key", body: "在控制台拿一把 sk-cs- 开头的密钥。" },
          { title: "替换 base_url", body: "把 SDK 的 base_url 指向 Market 即可。" },
        ],
      },
      howToProvider: {
        title: "我是 Token Provider",
        steps: [
          { title: "上架 share", body: "在 cc-switch 中把 share 设为 ForSale=Yes。" },
          { title: "选择本 Market", body: "Market 的 email 会自动加入 share 授权列表。" },
          { title: "等调用形成收益", body: "API 用户消费会按 token 价进入你的收益池。" },
          { title: "来 /claim 提现", body: "Gate.io 一键提现，或开工单走其他收款方式。" },
        ],
      },
      howToCurlTitle: "示例：替换 base_url 即可调用",
      curlTabs: {
        claude: "Claude",
        codex: "Codex",
        gemini: "Gemini",
        copy: "复制",
        copied: "已复制",
        copyToastTitle: "命令已复制",
        copyToastDesc: "请在终端粘贴并替换 sk-cs-…。",
        copyFailed: "复制失败",
        copyFailedDesc: "请手动选中文本复制。",
      },
      finalCtaTitle: "开始调用，或者开始出售",
      finalCtaSubtitle: "一个入口接入 AI 调用，一个市场承接 Provider 收益。不用密码，不用信用卡。",
      finalCtaApi: "我要接入 API",
      finalCtaProvider: "我是 Provider",
    },
    footer: {
      tagline: "AI Token 交易市场",
      legal: "© 2026 cc-switch Market · 保留所有权利。",
      builtWith: "全部记入账本，公开可对账。",
    },
    board: {
      title: "数据看板",
      subtitle: "市场实时数据。所有指标按 Market 时区切日，账本聚合公开可查。",
      windowLabel: "时间窗",
      windows: {
        "24h": "24 小时",
        "7d": "7 天",
        "30d": "30 天",
      },
      refresh: "刷新",
      refreshing: "刷新中…",
      lastUpdated: (when: string) => `最近更新 ${when}`,
      privacyNotice: "数据来自账本聚合：包含邮箱、消费、收益。API Key 永远不公开。",
      emptyDay: "暂无数据",
      kpis: {
        totalSpend: "总消费",
        totalRequests: "总调用",
        totalTopup: "总充值",
        activeApiUsers: "活跃 API 用户",
        activeProviders: "活跃 Provider",
        registeredUsers: "注册用户",
        onlineShares: "在线 share",
      },
      trend: {
        title: "充值与消费走势",
        subtitle: "按 Market 时区切日；金额单位 USD",
        seriesSpend: "消费",
        seriesTopup: "充值",
      },
      breakdown: {
        appType: "调用入口占比",
        model: "Top 模型消费占比",
        provider: "Top Provider 收益占比",
      },
      topModels: {
        title: "热门模型 Top",
        colAppType: "入口",
        colModel: "模型",
        colSpend: "消费",
        colRequests: "调用",
        colUsers: "用户数",
      },
      topProviders: {
        title: "Provider 收益榜",
        subtitle: "按 settled 时间窗口内成交金额排序，邮箱明文展示。",
        colEmail: "Provider 邮箱",
        colSpend: "成交金额",
        colRequests: "调用",
        colShares: "Share 数",
      },
      topUsers: {
        title: "API 用户消费榜",
        subtitle: "按 settled 时间窗口内消费排序，邮箱明文展示。",
        colEmail: "用户邮箱",
        colSpend: "消费",
        colRequests: "调用",
      },
      selfService: {
        title: "查我的账户",
        body: "用注册邮箱登录控制台，可看到自己的余额、API key 和明细记录。",
        cta: "去控制台",
        ctaProvider: "去 /claim 看收益",
      },
      empty: {
        title: "还没有数据",
        body: "看板需要至少一笔结算后的请求或一笔已支付订单才会有读数。",
      },
      error: {
        title: "加载失败",
        retry: "重试",
      },
      seeAll: "查看全部",
    },
    dashboard: {
      title: "控制台",
      subtitleAuthed: (email: string) => `已登录 · ${email}`,
      subtitleAnon: "登录后查看余额、API key 和调用记录",
      tabs: {
        overview: "概览",
        wallet: "钱包",
        keys: "API 密钥",
        usage: "用量",
      },
      adminDeniedTitle: "权限不足",
      adminDeniedDesc: "该页面仅管理员可访问。",
      overview: {
        statBalance: "可用余额",
        statLocked: "锁定中",
        statKeys: "在用密钥",
        statRecent: "最近活动",
        recentTitle: "最近活动",
        emptyTitle: "还没动静",
        emptyHint: "充值或跑一次 API，这里就开始记。",
      },
      wallet: {
        balance: "可用余额",
        lockedPrefix: "锁定中",
        topup: "充值",
        emptyTitle: "还没有资金变化",
        emptyHint: "充值或调用 API 后这里会有记录。",
        colType: "类型",
        colAmount: "金额",
        colAccount: "账户",
        colRef: "请求引用",
        colTime: "时间",
        topupModalTitle: "充值",
        topupModalDesc: "Dodo Payments 单次充值。手续费会单独显示，到账金额按 net 入账。",
        topupAmountLabel: "金额（USD）",
        topupCancel: "取消",
        topupSubmit: "去支付",
        topupSubmitting: "创建中…",
        topupErrorInvalid: "金额无效",
        topupErrorInvalidDesc: "请输入大于 0 的 USD 金额。",
        topupFirstLimitDesc: "首冲最多 10$，建议先小额体验后再充值更多",
        topupOrderCreated: "订单已创建",
        topupOrderNoUrl: "未返回支付链接，请稍后再试。",
        topupErrorTitle: "充值失败",
        topupPaidTitle: "充值已到账",
        topupStatusTitle: (s: string) => `充值状态：${s}`,
        topupNetDesc: (n: string) => `净入账 $${n}`,
      },
      keys: {
        title: "API 密钥",
        subtitle: "用 sk-cs- 开头的密钥调用兼容 API；不要把它写进前端代码。",
        anonTitle: "先登录",
        anonHint: "登录后再来创建、暂停或删除密钥。",
        openLogin: "打开登录窗口",
        createBtn: "新建密钥",
        emptyTitle: "还没有 API 密钥",
        emptyHint: "创建一把密钥，就能开始调用 OpenAI / Anthropic 兼容 API。",
        emptyAction: "新建密钥",
        colName: "名称",
        colKey: "密钥",
        colStatus: "状态",
        colLimits: "限制",
        colLast: "最近使用",
        colActions: "操作",
        statusPaused: "已暂停",
        statusActive: "已激活",
        actionEdit: "编辑",
        actionShares: "Share 限制",
        actionPause: "暂停",
        actionActivate: "激活",
        actionDelete: "删除",
        lastNever: "从未",
        copyTitle: "复制完整密钥",
        copyDisabledTitle: "当前没有可复制的明文密钥",
        copyAria: "复制完整密钥",
        copied: "已复制",
        copyFailed: "复制失败，请手动选择文本",
        createTitle: "新建 API 密钥",
        createDesc: "创建后可在表格的密钥列复制完整密钥。",
        createNameLabel: "名称",
        createNamePlaceholder: "例如：本地开发",
        unlimited: "无限制",
        custom: "自定义",
        unlimitedDefault: "默认不限制。",
        expiresLabel: "过期时间",
        spendCapLabel: "最大费用",
        spendCapHint: "按自然月统计，单位 USD。",
        modelScopeLabel: "授权模型",
        modelScopeHint: "默认允许调用所有当前支持的模型。",
        modelsLoading: "正在加载模型…",
        modelsEmpty: "暂无可授权模型",
        limitExpires: "过期",
        limitSpend: "月费用",
        limitModels: "模型",
        modelCount: (count: number) => `${count} 个模型`,
        shareTitle: "Share 限制",
        shareDesc: (name: string, prefix: string) =>
          `${name}（${prefix}…）只会在选中的 Share 中路由；不选择则自动使用所有可用 Share。`,
        shareAutoMode: "当前自动选择所有可用 Share。",
        shareLimitedMode: (count: number) => `当前仅使用已选择的 ${count} 个 Share。`,
        sharesLoading: "正在加载 Share…",
        sharesEmpty: "暂无可选择的 Share",
        shareOffline: "离线",
        shareClear: "清空限制",
        shareSaved: "Share 限制已保存",
        editTitle: "编辑 API 密钥",
        editDesc: (name: string, prefix: string) =>
          `${name}（${prefix}…）的名称和限制会在保存后更新。`,
        editSave: "保存",
        editSaving: "保存中…",
        editSaved: "已保存",
        editFailed: "保存失败",
        createCancel: "取消",
        createSubmit: "创建",
        createSubmitting: "创建中…",
        createSuccess: "密钥已创建",
        createFailed: "创建失败",
        defaultName: "默认密钥",
        pauseTitle: "暂停密钥",
        pauseDesc: (name: string, prefix: string) =>
          `${name}（${prefix}…）暂停后立即失效，但可重新激活。`,
        pauseConfirm: "确认暂停",
        paused: "已暂停",
        activateTitle: "激活密钥",
        activateDesc: (name: string, prefix: string) =>
          `${name}（${prefix}…）激活后可重新用于 API 调用。`,
        activateConfirm: "确认激活",
        activated: "已激活",
        deleteTitle: "删除密钥",
        deleteDesc: "只有已暂停的密钥才能删除。删除后将不再显示，浏览器保存的明文记录也会一并移除。",
        deleteConfirm: "确认删除",
        deleted: "已删除",
        operationFailed: "操作失败",
      },
      usage: {
        emptyTitle: "还没有调用记录",
        emptyHint: "跑一次 OpenAI / Anthropic 兼容请求，这里就会出现明细。",
        colRequest: "Request ID",
        colModel: "模型",
        colShare: "Share",
        colTokens: "Token",
        colAmount: "金额",
        colStatus: "状态",
        colTime: "时间",
        colActions: "操作",
        report: "举报",
        reportCreated: "举报工单已创建",
        reportExisting: "已打开已有举报工单",
        reportFailed: "举报失败",
        snapshotTitle: "价格快照",
        cacheReadPrefix: "缓存读",
        cacheWritePrefix: "缓存写",
        loadMore: "加载更多",
        loading: "加载中…",
      },
      events: {
        topup: "充值",
        topupFee: "充值手续费",
        usage: "消费",
        usageReserved: "消费预授权",
        usageRelease: "预授权退回",
        platformCommission: "Market 抽成",
        marketCommissionWithRate: "Market 抽成（{rate}）",
        routerCommission: "Router 抽成",
        routerCommissionWithRate: "Router 抽成（{rate}）",
        ledgerEntry: "账本流水",
        providerIncome: "Provider 收入",
        providerEarningToBalance: "收益转余额",
        providerEarningTransfer: "Provider 收益转账",
        payout: "提现",
        payoutFee: "提现手续费",
        payoutReserved: "提现锁定",
        payoutReleased: "提现释放",
        refund: "退款",
        adjustment: "人工调账",
        fallback: "事件",
      },
    },
    claim: {
      title: "Provider 收益",
      subtitleEmail: (email: string) => `归属邮箱：${email}`,
      subtitleAnon: "登录邮箱 = 收益归属邮箱",
      anonTitle: "先登录",
      anonHint: "用你 share 的 owner email 登录，收益会自动归到这里。",
      openLogin: "打开登录窗口",
      statAvailable: "可提现",
      statLocked: "锁定中",
      statPaid: "已结算",
      thresholdTitle: (diff: string) => `再赚 $${diff} 即可提现`,
      thresholdHint: (min: string) =>
        `待提现余额 ≥ $${min} 才能发起。先在 cc-switch 把 share 设为 ForSale=Yes 并选择本 Market。`,
      gateioTitle: "Gate.io 自动提现",
      gateioBody: "填邮箱或 UID，系统自动发起转账。",
      gateioBtn: "发起提现",
      manualTitle: "其他收款方式",
      manualBody: "开工单写收款详情，由管理员手动打款。",
      manualBtn: "创建工单",
      balanceTitle: "转入 API 余额",
      balanceBody: "把可提现收益转为当前账号的钱包余额，可直接用于 API 消费。",
      balanceBtn: "转入余额",
      providerTransferTitle: "转给其他 Provider",
      providerTransferBody: "把可提现收益转给另一个 owner email，进入对方 Provider 收益余额。",
      providerTransferBtn: "转给 Provider",
      payoutsTitle: "结算记录",
      earningsTitle: "收益明细",
      earningsSubtitle: (rate: string) =>
        `每笔 API 用户消费形成的收入，可按 request id 对账。当前总抽成为 ${rate}。`,
      payoutsEmptyTitle: "还没有提现记录",
      payoutsEmptyHint: "发起一笔提现后，状态会出现在这里。",
      earningsEmptyTitle: "还没有收入",
      earningsEmptyHint: "API 用户消费产生的收入会出现在这里。",
      payoutCol: {
        method: "方式",
        amount: "金额",
        status: "状态",
        external: "凭证",
        time: "时间",
      },
      earningsCol: {
        request: "Request ID",
        model: "模型",
        status: "状态",
        amount: "收入",
      },
      failureLabel: "失败原因：",
      gateioModalTitle: "Gate.io 自动提现",
      gateioModalDesc: "USD 等值会按当前 USD/USDT 比例转出至 Gate.io 现货账户。",
      gateioAmountLabel: "提现金额（USD）",
      gateioMaxHint: (max: string) => `最多 $${max}`,
      gateioByEmail: "用邮箱",
      gateioByUid: "用 UID",
      gateioEmailPlaceholder: "seller@example.com",
      gateioUidPlaceholder: "Gate.io UID",
      submitCancel: "取消",
      submitSubmit: "提交提现",
      submitSubmitting: "提交中…",
      submitInvalidEmail: "请填写有效的 Gate.io 邮箱",
      submitInvalidUid: "请填写 Gate.io UID",
      submitSuccess: "提现已提交",
      submitSuccessDesc: "Gate.io 调用结果会出现在提现记录中。",
      submitFailed: "提交失败",
      manualModalTitle: "其他收款方式",
      manualModalDesc: "将创建提现工单并锁定余额，由管理员手动打款后结算。",
      manualAmountLabel: "提现金额（USD）",
      manualDetailsLabel: "收款方式与备注",
      manualDetailsPlaceholder: "USDT TRC20 地址、姓名、手机等信息",
      manualSubmit: "创建工单",
      manualMissingDetails: "请填写收款方式与备注",
      manualSuccess: "工单已创建",
      manualSuccessDesc: "余额已锁定，等待管理员处理。",
      balanceModalTitle: "转入 API 余额",
      balanceModalDesc: "转入后会从可提现收益扣除，进入钱包可用余额。此操作不可撤销。",
      balanceAmountLabel: "转入金额（USD）",
      balanceSubmit: "确认转入",
      balanceSuccess: "已转入余额",
      providerTransferModalTitle: "转给其他 Provider",
      providerTransferModalDesc: "转账会立即完成，进入目标 owner email 的 Provider 收益余额。此操作不可撤销。",
      providerTransferAmountLabel: "转账金额（USD）",
      providerTransferEmailLabel: "目标 owner email",
      providerTransferEmailPlaceholder: "provider@example.com",
      providerTransferSubmit: "确认转账",
      providerTransferSuccess: "已转给 Provider",
      internalTransferInvalidAmount: "请输入有效金额",
      internalTransferInvalidAmountDesc: "金额必须大于 0，且不能超过可提现余额。",
      internalTransferInvalidEmail: "请填写有效的目标 owner email",
      internalTransferFailed: "转账失败",
      payoutMethodGateio: "Gate.io 自动提现",
      payoutMethodManual: "人工提现",
      payoutMethodBalance: "转入 API 余额",
      payoutMethodProvider: "转给 Provider",
      payoutMethodProviderReceived: "接收 Provider",
      payoutMethodRouterCommission: "Router 抽成",
      filePickerLabel: "选择图片（PNG/JPG/WebP，≤ 2MB）",
      attachmentsTitle: "图片附件",
      lightboxClose: "关闭图片预览",
      attachmentFallback: "图片",
    },
    support: {
      title: "工单",
      detailTitle: "工单详情",
      subtitle: "充值、提现、调用、账号问题，都从这里进入。附件保存在对象存储中。",
      detailSubtitle: (no: string, hint: string) => `${no} · ${hint}`,
      statusYourTurn: "等你回复",
      statusOurTurn: "等我们处理",
      statusEnded: "已结束",
      statusViewing: "查看和回复当前工单",
      backToList: "返回工单列表",
      newTicket: "新建工单",
      anonTitle: "先登录",
      anonHint: "登录后才能查看、创建和回复工单。",
      openLogin: "打开登录窗口",
      view: {
        all: (n: number) => `全部 ${n}`,
        mine: (n: number) => `等你回复 ${n}`,
        platform: (n: number) => `等我们 ${n}`,
        done: (n: number) => `已结束 ${n}`,
      },
      filterStatusLabel: "状态筛选",
      filterStatusOptions: {
        all: "全部",
        open: "待接",
        waitingAdmin: "等管理员",
        waitingUser: "等用户",
        resolved: "已解决",
        closed: "已关闭",
      },
      filterPriorityLabel: "优先级筛选",
      priority: {
        all: "全部",
        low: "低",
        normal: "中",
        high: "高",
        urgent: "紧急",
      },
      type: {
        feedback: "使用反馈",
        billing_issue: "钱的事",
        account_issue: "账号 / 密钥",
        payout_manual: "人工提现",
      },
      noMatchTitle: "没有匹配的工单",
      noMatchHint: "试试切换状态或优先级筛选。",
      emptySubject: "（无主题）",
      createTitle: "新建工单",
      createDesc: "仅支持图片附件，单个不超过 2 MB。",
      categoryLabel: "类别",
      category: {
        feedback: "使用反馈 · bug · 需求",
        billing: "充值 / 扣费 / 退款问题",
        account: "账号 / API key",
      },
      priorityLabel: "优先级",
      subjectLabel: "主题",
      subjectPlaceholder: "一句话描述问题",
      bodyLabel: "详细描述",
      bodyPlaceholder: "提供 request id、复现步骤、期望与实际结果。",
      cancel: "取消",
      submit: "提交",
      submitting: "提交中…",
      submitMissing: "请填写主题和内容",
      submitSuccess: "工单已创建",
      submitFailed: "创建失败",
      replyMissing: "请输入回复内容",
      replyFailed: "回复失败",
      closeBtn: "关闭工单",
      closeConfirmTitle: "关闭工单？",
      closeOk: "确认关闭",
      closeFailed: "关闭失败",
      closeSuccess: "工单已关闭",
      deleteBtn: "删除",
      deleteConfirmTitle: "删除工单？",
      deleteOk: "确认删除",
      deleteFailed: "删除失败",
      deleteSuccess: "工单已删除",
    },
    admin: {
      title: "管理后台",
      subtitle: "用户、供给、资金、工单与审计的统一入口。所有写入都会记入 admin_audit。",
      tabs: {
        overview: "概览",
        users: "用户",
        models: "模型",
        shares: "Shares",
        money: "资金",
        tickets: "工单",
        announcements: "公告",
        settings: "设置",
        audit: "审计",
      },
      ledgerOk: "账本对得上",
      ledgerBad: "账本对不上",
      ledgerChecking: "校验中",
      overview: {
        todayTopups: "今日充值",
        todayUsage: "今日消费",
        needsReview: "待复核",
        pendingPayouts: "待打款",
        openTickets: "待回复工单",
        ledger: "账本",
        ledgerOk: "对得上",
        ledgerBad: "对不上",
      },
      users: {
        emptyTitle: "还没有用户",
        colEmail: "邮箱",
        colStatus: "状态",
        colBalance: "可用 / 锁定",
        colCreated: "注册时间",
        colActions: "操作",
        actionAdjust: "调账",
        adjustTitle: "人工调账",
        adjustCredit: "+ 加余额",
        adjustDebit: "− 扣余额",
        adjustReasonPlaceholder: "原因（必填，记入 admin_audit）",
        adjustCancel: "取消",
        adjustSubmit: "确认调账",
        adjustReasonMissing: "请填写原因",
        adjustSuccess: "已调账",
        adjustFailed: "调账失败",
      },
      models: {
        addBtn: "+ 新模型",
        emptyTitle: "还没配置模型",
        emptyHint: "新增并设置价格后，API 用户才能调用。",
        colType: "类型",
        colPattern: "模型",
        colInput: "输入 / 1M",
        colOutput: "输出 / 1M",
        colRouting: "路由",
        colStatus: "状态",
        colActions: "操作",
        actionEdit: "编辑",
        actionShare: "Share",
        actionOnline: "上线",
        actionOffline: "下线",
        actionDelete: "删除",
        deleteConfirm: (pattern: string) =>
          `确认删除模型 ${pattern}？此操作只允许删除已下线模型。`,
        deletedToast: "模型已删除",
        deleteFailed: "删除失败",
        onlineToast: "模型已上线",
        offlineToast: "模型已下线",
        statusOpFailed: "操作失败",
        editorTitleNew: "新增模型",
        editorTitleEdit: "编辑模型",
        editorReasonMissing: "请填写改价原因",
        savedToast: "已保存模型",
        saveFailed: "保存失败",
      },
      topups: {
        emptyTitle: "还没有充值订单",
        colId: "订单",
        colAmount: "金额",
        colStatus: "状态",
        colTime: "时间",
        colActions: "操作",
        actionRefund: "退款",
        refundTitle: "充值退款",
        refundOrder: (id: string) => `订单 ${id}`,
        refundReasonPlaceholder: "退款原因",
        refundFeeLabel: "同时退还充值手续费",
        refundCancel: "取消",
        refundSubmit: "确认退款",
        refundReasonMissing: "请填写退款原因",
        refundSuccess: "已记录退款",
      },
      shares: {
        title: "Router shares",
        syncBtn: "手动同步",
        syncOk: "已触发同步",
        syncFailed: "同步失败",
        emptyTitle: "还没有 share 缓存",
      },
      money: {
        workspaceTitle: "资金工作台",
        workspaceSubtitle:
          "充值、计费、收益、提现、事件、账本，统一入口查询。底层数据源独立。",
        tabs: {
          overview: "总览",
          events: "事件流",
          charges: "API 计费",
          earnings: "Provider 收益",
          topups: "充值",
          payouts: "提现",
          ledger: "账本",
          check: "对账检查",
        },
        overview: {
          todayTopups: "今日充值",
          todayUsage: "今日消费",
          providerPayable: "Provider 应付",
          routerPayable: "Router 应付",
          payoutReserved: "待提现锁定",
          userCash: "用户余额",
          userReserved: "预授权中",
          feeRevenue: "手续费 / 抽成收入",
          topupFees: "充值手续费",
          platformTakeRevenue: "Market 抽成",
          payoutFees: "提现手续费",
          platformCommission: "平台抽成",
          marketCommission: "Market",
          routerCommission: "Router",
          riskLoss: "风控损失",
          pendingTopups: "待支付",
          needsReview: "待复核计费",
          pendingPayouts: "待处理提现",
          consistencyTitle: "账本一致性",
          consistencyBody: "账户缓存必须与账本聚合一致。",
          consistencyOk: "对得上",
          consistencyBad: "对不上",
        },
        emptyEvents: "还没有资金事件",
        emptyCharges: "还没有 API 计费",
        emptyEarnings: "尚无 Provider 应付汇总",
        emptyLedger: "账本暂无条目",
        emptyCheck: "对账检查暂无结果",
      },
      payouts: {
        emptyTitle: "还没有提现请求",
        colOwner: "Owner",
        colAmount: "金额",
        colMethod: "方式",
        colStatus: "状态",
        colExternal: "external tx",
        colActions: "操作",
        actionExecute: "执行 Gate.io",
        actionMarkPaid: "标记已付",
        actionMarkFailed: "标记失败",
        actionCancel: "取消",
        executeTitle: "执行 Gate.io 提现",
        executeReasonPlaceholder: "备注（可选）",
        executeConfirm: "执行",
        markFailedTitle: "标记失败",
        markFailedReasonPlaceholder: "失败原因",
        markFailedConfirm: "标记失败",
        cancelTitle: "取消提现",
        cancelReasonPlaceholder: "取消原因",
        cancelConfirm: "取消提现",
        markPaidTitle: "标记提现已完成",
        markPaidExternalPlaceholder: "external tx id",
        markPaidProofPlaceholder: "凭证说明",
        markPaidConfirm: "确认完成",
        markPaidExternalMissing: "请填写 external tx id",
        markPaidProofMissing: "请填写凭证说明",
        markPaidSuccess: "已标记完成",
        opFailed: "操作失败",
        opSuccess: "已操作",
        opExecuted: "已执行",
        reasonMissing: "请填写原因",
      },
      announcements: {
        addBtn: "+ 新公告",
        copyJson: "复制 JSON",
        edit: "编辑",
        delete: "删除",
        emptyTitle: "暂无公告",
        manageTitle: "公告管理",
        manageBody:
          "公告事实源是浏览器本地存储。在这里增删改会立刻影响导航铃铛与公告弹窗。",
        copied: "已复制公告 JSON",
        savedNew: "公告已新增",
        savedEdit: "公告已更新",
        deleted: "公告已删除",
        editorTitleNew: "新增公告",
        editorTitleEdit: "编辑公告",
        deleteTitle: "删除公告",
        deleteConfirmBody: (title: string) => `确认删除公告：${title}`,
      },
      settings: {
        title: "设置",
        subtitle: "管理时区、环境变量和运行参数。修改写入磁盘上的 .env 文件。",
        tabs: {
          system: "系统",
        },
        categories: {
          runtime: "运行",
          auth: "认证",
          cloudflare: "Cloudflare",
          billing: "计费",
          routing: "路由",
          database: "数据库",
          storage: "存储",
          router: "Router",
          payments: "收付款",
        },
        system: {
          timeZoneLabel: "系统时区",
          timeZoneCurrent: "当前显示",
          timeZoneDefaultSuffix: "默认",
          tablePageSizeLabel: "管理表格每页行数",
          tablePageSizeCurrent: (n: number) => `当前每页 ${n} 行`,
          tablePageSizeHint: "适用于管理后台所有表格，保存后立即生效。范围 1-500。",
          tablePageSizeSavedToast: "表格分页已保存",
          savedToast: "时区已保存",
          saveFailed: "保存失败",
        },
        env: {
          envFileLabel: ".env 文件",
          hint: "修改会写入 .env；运行中的 market 进程不会自动热加载，重启后生效。",
          unsavedSummary: (n: number) => `${n} 项未保存`,
          noUnsaved: "无未保存改动",
          save: "保存 .env",
          reset: "全部重置",
          resetAll: "重置全部修改",
          resetField: "撤销改动",
          restoreDefault: "恢复默认",
          reveal: "显示",
          hide: "隐藏",
          copy: "复制",
          copied: "已复制",
          empty: "未填",
          defaultLabel: "默认",
          required: "必填",
          optional: "可选",
          modified: "已修改",
          unitSecs: "秒",
          unitDays: "天",
          unitBps: "bps",
          unitUsd: "USD",
          boolOn: "启用",
          boolOff: "停用",
          savedToast: ".env 已保存",
          savedDesc: "运行中的进程需要重启后才会读取新的环境变量。",
          saveFailed: "保存失败",
          previewTitle: "确认变更",
          previewBody: (n: number) => `共 ${n} 项变更将写入 .env：`,
          previewCancel: "取消",
          previewConfirm: "确认写入",
          unchanged: "（未改动）",
          beforeUnload: "你有未保存的环境变量改动，确定要离开？",
        },
        footerLinks: {
          title: "底部页脚链接",
          subtitle: "对外页面的页脚展示项，按顺序在所有页面底部出现。每列固定 3 行，超出自动换列。",
          add: "+ 新增链接",
          save: "保存页脚",
          reset: "全部重置",
          empty: "还没有页脚链接，点 + 新增链接 添加。",
          colIcon: "图标",
          colLabelZh: "中文标签",
          colLabelEn: "英文标签",
          colUrl: "链接",
          colActions: "操作",
          moveUp: "上移",
          moveDown: "下移",
          remove: "删除",
          urlPlaceholder: "https://example.com",
          labelZhPlaceholder: "例如：文档",
          labelEnPlaceholder: "e.g. Docs",
          unsavedSummary: (n: number) => `${n} 项未保存`,
          noUnsaved: "无未保存改动",
          countSummary: (n: number, max: number) => `已添加 ${n} / ${max}`,
          limitReached: "已达到上限",
          savedToast: "页脚已保存",
          savedDesc: "公开页面已立即生效。",
          saveFailed: "保存失败",
          beforeUnload: "页脚有未保存改动，确定要离开？",
          errorMissingLabel: "中英文标签至少填一个",
          errorMissingUrl: "请填链接",
          errorBadUrl: "链接必须以 https://、http://、/ 或 mailto: 开头",
        },
      },
      audit: {
        emptyTitle: "尚无审计记录",
      },
    },
  },
  en: {
    nav: {
      home: "Home",
      dashboard: "Console",
      claim: "Earnings",
      support: "Support",
      board: "Insights",
      admin: "Admin",
      announcements: "Announcements",
      menu: "Menu",
    },
    auth: {
      login: "Sign in",
      logout: "Sign out",
      checking: "Checking",
      admin: "Admin",
      loginTitle: "Sign in with email",
      loginDescEmail: "Drop your email — we'll send a 6-digit code.",
      loginDescCode: "Type the 6-digit code we sent.",
      email: "Email",
      code: "6-digit code",
      sendCode: "Send code",
      verifyLogin: "Sign in",
      changeEmail: "Change email",
      loginSuccess: "Signed in",
      turnstileRequired: "Please complete the human verification first.",
      turnstileFailed: "Human verification failed to load. Please refresh and try again.",
    },
    common: {
      themeLight: "Light",
      themeDark: "Dark",
      language: "Language",
      chinese: "中文",
      english: "English",
      close: "Close",
    },
    landing: {
      heroBadge: "platform take · public pricing · live in 30s",
      heroBrand: "cc-switch Market",
      heroH1Prefix: "An AI token",
      heroH1Highlight: "marketplace",
      heroSubtitle:
        "Buy capability as an API user. Sell capacity as a token provider. OpenAI / Anthropic compatible, transparent pricing, payout-ready earnings.",
      heroPricePromise: "Every model is available at 1/10 of the official reference price.",
      heroCtaPrimary: "Open the console",
      heroCtaSecondary: "I'm a Provider",
      heroPricingLink: "See pricing →",
      metrics: [
        { label: "Every model", value: "1/10 official price" },
        { label: "Public pricing", value: "transparent settlement" },
        { label: "Payout ready", value: "Gate.io · ticket fallback" },
      ],
      flowTitle: "From an API call to provider earnings",
      flowSubtitle:
        "User calls → market routes & bills → provider earns. Every cent traceable by request id.",
      flowSteps: [
        { label: "API user", note: "Authorization: sk-cs-…" },
        { label: "Market", note: "Pre-auth · billing" },
        { label: "Router", note: "Injects X-Share-Token" },
        { label: "cc-switch", note: "Local proxy" },
        { label: "Upstream", note: "OpenAI · Anthropic" },
      ],
      flowStepBadge: (i: number) => `Step ${i}`,
      featuresTitle: "Why use this market",
      features: [
        {
          title: "Every cent on the ledger",
          body: "Top-ups, spend, payouts, refunds — all traceable.",
        },
        {
          title: "Public platform take",
          body: "User spend, platform take, and provider net income are all recorded on the ledger.",
        },
        {
          title: "Billed as it streams",
          body: "We tee the SSE, parse usage, charge by real tokens. No estimates.",
        },
        {
          title: "Lock first, spend later",
          body: "Tiny pre-auth before each call. No surprises, no shortfall.",
        },
        {
          title: "Change one URL, ship",
          body: "OpenAI, Anthropic, Gemini SDKs all accept this base_url.",
        },
        {
          title: "Stuck? A human steps in",
          body: "Gate.io auto first. If it stalls, file a ticket — we wire by hand.",
        },
      ],
      pricingTitle: "Public pricing",
      pricingSubtitle:
        "Market calls are shown at 1/10 of the official reference price, with the combined Market + Router take disclosed.",
      pricingBadge: "Platform take",
      pricingCol: {
        model: "Model",
        input: "Input / 1M",
        output: "Output / 1M",
        cacheRead: "Cache R / 1M",
        cacheWrite: "Cache W / 1M",
        inputShort: "Input",
        outputShort: "Output",
        cacheReadShort: "Cache R",
        cacheWriteShort: "Cache W",
      },
      pricingEmpty: {
        title: "No prices yet",
        body: "Once the admin sets a unified token price, it will appear here.",
      },
      pricingProviderEmpty: {
        title: (provider: string) => `No ${provider} prices yet`,
        body: "Once the admin configures it, it'll show in this tab.",
      },
      pricingFooter:
        "Strikethrough is the official reference price; bold is the market's current price. Empty cells mean the official side hasn't published that line item. Models not listed here still bill via fallback rules.",
      pricingPageInfo: (current: number, total: number, count: number) =>
        `Page ${current} / ${total} · ${count} rows`,
      pricingPrev: "Prev",
      pricingNext: "Next",
      howToTitle: "Easy on both sides",
      howToSubtitle: "API users plug in; providers list. A handful of steps each.",
      howToApi: {
        title: "I'm an API user",
        steps: [
          { title: "Sign in & top up", body: "Email code login. One-time card payment via Dodo." },
          { title: "Create an API key", body: "Grab a sk-cs- key in the console." },
          { title: "Swap your base_url", body: "Point your SDK at the market — done." },
        ],
      },
      howToProvider: {
        title: "I'm a token provider",
        steps: [
          { title: "List your share", body: "In cc-switch, set ForSale=Yes on the share." },
          {
            title: "Pick this market",
            body: "The market's email is added to the share's authorized list automatically.",
          },
          { title: "Earn on calls", body: "API user spend lands in your earnings pool, by token price." },
          { title: "Cash out at /claim", body: "Gate.io payout, or open a ticket for other methods." },
        ],
      },
      howToCurlTitle: "Example: swap the base_url and call",
      curlTabs: {
        claude: "Claude",
        codex: "Codex",
        gemini: "Gemini",
        copy: "Copy",
        copied: "Copied",
        copyToastTitle: "Command copied",
        copyToastDesc: "Paste in your terminal and swap in your sk-cs-… key.",
        copyFailed: "Copy failed",
        copyFailedDesc: "Select the text manually to copy.",
      },
      finalCtaTitle: "Start calling, or start selling",
      finalCtaSubtitle:
        "One endpoint for AI calls, one market for provider earnings. No password. No card.",
      finalCtaApi: "I'll plug in the API",
      finalCtaProvider: "I'm a Provider",
    },
    footer: {
      tagline: "An AI token marketplace",
      legal: "© 2026 cc-switch Market · All rights reserved.",
      builtWith: "Every move recorded to the ledger. Verifiable end to end.",
    },
    board: {
      title: "Market insights",
      subtitle: "Real-time market data. Days bucketed by market timezone; aggregated from the ledger.",
      windowLabel: "Window",
      windows: {
        "24h": "24h",
        "7d": "7d",
        "30d": "30d",
      },
      refresh: "Refresh",
      refreshing: "Refreshing…",
      lastUpdated: (when: string) => `Updated ${when}`,
      privacyNotice: "Data is aggregated from the ledger and includes emails, spend, and provider revenue. API keys are never exposed.",
      emptyDay: "No data",
      kpis: {
        totalSpend: "Total spend",
        totalRequests: "Total requests",
        totalTopup: "Total top-ups",
        activeApiUsers: "Active API users",
        activeProviders: "Active providers",
        registeredUsers: "Registered users",
        onlineShares: "Live shares",
      },
      trend: {
        title: "Top-ups vs spend",
        subtitle: "Days bucketed by market timezone; amounts in USD",
        seriesSpend: "Spend",
        seriesTopup: "Top-ups",
      },
      breakdown: {
        appType: "Calls by app type",
        model: "Spend by model",
        provider: "Spend by provider",
      },
      topModels: {
        title: "Top models",
        colAppType: "App",
        colModel: "Model",
        colSpend: "Spend",
        colRequests: "Calls",
        colUsers: "Users",
      },
      topProviders: {
        title: "Top providers",
        subtitle: "Ranked by gross spend routed within the window. Emails shown in clear.",
        colEmail: "Provider email",
        colSpend: "Gross",
        colRequests: "Calls",
        colShares: "Shares",
      },
      topUsers: {
        title: "Top API spenders",
        subtitle: "Ranked by spend in the window. Emails shown in clear.",
        colEmail: "User email",
        colSpend: "Spend",
        colRequests: "Calls",
      },
      selfService: {
        title: "Find my account",
        body: "Sign in with your registered email to see your balance, keys and call history.",
        cta: "Go to console",
        ctaProvider: "View earnings at /claim",
      },
      empty: {
        title: "No data yet",
        body: "Insights need at least one settled call or one paid top-up to produce numbers.",
      },
      error: {
        title: "Failed to load",
        retry: "Retry",
      },
      seeAll: "See all",
    },
    dashboard: {
      title: "Console",
      subtitleAuthed: (email: string) => `Signed in · ${email}`,
      subtitleAnon: "Sign in to view balance, API keys and request history",
      tabs: {
        overview: "Overview",
        wallet: "Wallet",
        keys: "API keys",
        usage: "Usage",
      },
      adminDeniedTitle: "Not allowed",
      adminDeniedDesc: "This page is admin-only.",
      overview: {
        statBalance: "Balance",
        statLocked: "Locked",
        statKeys: "Active keys",
        statRecent: "Recent activity",
        recentTitle: "Recent activity",
        emptyTitle: "Nothing yet",
        emptyHint: "Top up or fire a request — it'll show here.",
      },
      wallet: {
        balance: "Available",
        lockedPrefix: "Locked",
        topup: "Top up",
        emptyTitle: "No money moves yet",
        emptyHint: "Top-ups and API calls show up here.",
        colType: "Type",
        colAmount: "Amount",
        colAccount: "Accounts",
        colRef: "Request ref",
        colTime: "Time",
        topupModalTitle: "Top up",
        topupModalDesc:
          "One-time payment via Dodo Payments. Fees are shown separately; net is credited.",
        topupAmountLabel: "Amount (USD)",
        topupCancel: "Cancel",
        topupSubmit: "Pay",
        topupSubmitting: "Creating…",
        topupErrorInvalid: "Invalid amount",
        topupErrorInvalidDesc: "Please enter a USD amount greater than 0.",
        topupFirstLimitDesc:
          "First top-up is limited to $10. Try a small amount first, then top up more.",
        topupOrderCreated: "Order created",
        topupOrderNoUrl: "No payment URL returned. Please try again.",
        topupErrorTitle: "Top up failed",
        topupPaidTitle: "Top up credited",
        topupStatusTitle: (s: string) => `Top-up status: ${s}`,
        topupNetDesc: (n: string) => `Net credited $${n}`,
      },
      keys: {
        title: "API keys",
        subtitle: "Use sk-cs- keys to call the compatible API. Don't bake them into frontend code.",
        anonTitle: "Sign in first",
        anonHint: "Sign in to create, pause or delete API keys.",
        openLogin: "Open sign-in",
        createBtn: "New key",
        emptyTitle: "No API keys yet",
        emptyHint: "Create a key — you'll be calling the OpenAI / Anthropic compatible API in seconds.",
        emptyAction: "New key",
        colName: "Name",
        colKey: "Key",
        colStatus: "Status",
        colLimits: "Limits",
        colLast: "Last used",
        colActions: "Actions",
        statusPaused: "Paused",
        statusActive: "Active",
        actionEdit: "Edit",
        actionShares: "Share scope",
        actionPause: "Pause",
        actionActivate: "Activate",
        actionDelete: "Delete",
        lastNever: "Never",
        copyTitle: "Copy full key",
        copyDisabledTitle: "No clear-text key available right now",
        copyAria: "Copy full key",
        copied: "Copied",
        copyFailed: "Copy failed — please select the text manually",
        createTitle: "New API key",
        createDesc: "After creating, copy the full key from the Key column.",
        createNameLabel: "Name",
        createNamePlaceholder: "e.g. local dev",
        unlimited: "Unlimited",
        custom: "Custom",
        unlimitedDefault: "Unlimited by default.",
        expiresLabel: "Expires at",
        spendCapLabel: "Max spend",
        spendCapHint: "Calendar-month cap in USD.",
        modelScopeLabel: "Authorized models",
        modelScopeHint: "By default, all currently supported models are allowed.",
        modelsLoading: "Loading models…",
        modelsEmpty: "No models available",
        limitExpires: "Expires",
        limitSpend: "Monthly spend",
        limitModels: "Models",
        modelCount: (count: number) => `${count} model${count === 1 ? "" : "s"}`,
        shareTitle: "Share scope",
        shareDesc: (name: string, prefix: string) =>
          `${name} (${prefix}…) only routes through selected shares. Select none to use all available shares automatically.`,
        shareAutoMode: "Currently using all available shares automatically.",
        shareLimitedMode: (count: number) => `Currently limited to ${count} selected share${count === 1 ? "" : "s"}.`,
        sharesLoading: "Loading shares…",
        sharesEmpty: "No shares available",
        shareOffline: "Offline",
        shareClear: "Clear scope",
        shareSaved: "Share scope saved",
        editTitle: "Edit API key",
        editDesc: (name: string, prefix: string) =>
          `${name} (${prefix}…) name and limits are updated after saving.`,
        editSave: "Save",
        editSaving: "Saving…",
        editSaved: "Saved",
        editFailed: "Save failed",
        createCancel: "Cancel",
        createSubmit: "Create",
        createSubmitting: "Creating…",
        createSuccess: "Key created",
        createFailed: "Create failed",
        defaultName: "Default key",
        pauseTitle: "Pause key",
        pauseDesc: (name: string, prefix: string) =>
          `${name} (${prefix}…) becomes inactive immediately. You can re-activate later.`,
        pauseConfirm: "Confirm pause",
        paused: "Paused",
        activateTitle: "Activate key",
        activateDesc: (name: string, prefix: string) =>
          `${name} (${prefix}…) will be re-enabled for API calls.`,
        activateConfirm: "Confirm activate",
        activated: "Activated",
        deleteTitle: "Delete key",
        deleteDesc:
          "Only paused keys can be deleted. After deletion, the local clear-text record is also removed.",
        deleteConfirm: "Confirm delete",
        deleted: "Deleted",
        operationFailed: "Operation failed",
      },
      usage: {
        emptyTitle: "No requests yet",
        emptyHint: "Make one OpenAI / Anthropic compatible request and it'll show here.",
        colRequest: "Request ID",
        colModel: "Model",
        colShare: "Share",
        colTokens: "Tokens",
        colAmount: "Amount",
        colStatus: "Status",
        colTime: "Time",
        colActions: "Actions",
        report: "Report",
        reportCreated: "Report ticket created",
        reportExisting: "Existing report ticket opened",
        reportFailed: "Report failed",
        snapshotTitle: "Price snapshot",
        cacheReadPrefix: "Cache read",
        cacheWritePrefix: "Cache write",
        loadMore: "Load more",
        loading: "Loading…",
      },
      events: {
        topup: "Top up",
        topupFee: "Top-up fee",
        usage: "Spend",
        usageReserved: "Spend hold",
        usageRelease: "Hold released",
        platformCommission: "Market take",
        marketCommissionWithRate: "Market take ({rate})",
        routerCommission: "Router take",
        routerCommissionWithRate: "Router take ({rate})",
        ledgerEntry: "Ledger entry",
        providerIncome: "Provider income",
        providerEarningToBalance: "Earnings to balance",
        providerEarningTransfer: "Provider earnings transfer",
        payout: "Payout",
        payoutFee: "Payout fee",
        payoutReserved: "Payout locked",
        payoutReleased: "Payout released",
        refund: "Refund",
        adjustment: "Manual adjustment",
        fallback: "Event",
      },
    },
    claim: {
      title: "Provider earnings",
      subtitleEmail: (email: string) => `Owner email: ${email}`,
      subtitleAnon: "Your sign-in email is the earnings owner email",
      anonTitle: "Sign in first",
      anonHint: "Sign in with your share's owner email — earnings find you.",
      openLogin: "Open sign-in",
      statAvailable: "Available",
      statLocked: "Locked",
      statPaid: "Settled",
      thresholdTitle: (diff: string) => `$${diff} to go before payout`,
      thresholdHint: (min: string) =>
        `You need at least $${min} to cash out. In cc-switch, set ForSale=Yes on your share and pick this market.`,
      gateioTitle: "Gate.io auto payout",
      gateioBody: "Drop an email or UID — we wire it for you.",
      gateioBtn: "Start payout",
      manualTitle: "Other methods",
      manualBody: "File a ticket with payout details. We wire it by hand.",
      manualBtn: "File a ticket",
      balanceTitle: "Move to API balance",
      balanceBody:
        "Convert available provider earnings into this account's wallet balance for API spend.",
      balanceBtn: "Move to balance",
      providerTransferTitle: "Send to another Provider",
      providerTransferBody:
        "Move available earnings to another owner email's Provider earnings balance.",
      providerTransferBtn: "Send to Provider",
      payoutsTitle: "Settlements",
      earningsTitle: "Earnings",
      earningsSubtitle: (rate: string) =>
        `Each row is income from an API user call. Current total take is ${rate}. Match by request id.`,
      payoutsEmptyTitle: "No payouts yet",
      payoutsEmptyHint: "Once you start a payout, status changes show up here.",
      earningsEmptyTitle: "No earnings yet",
      earningsEmptyHint: "Income from API user calls will appear here.",
      payoutCol: {
        method: "Method",
        amount: "Amount",
        status: "Status",
        external: "Proof",
        time: "Time",
      },
      earningsCol: {
        request: "Request ID",
        model: "Model",
        status: "Status",
        amount: "Income",
      },
      failureLabel: "Failure reason:",
      gateioModalTitle: "Gate.io auto payout",
      gateioModalDesc:
        "USD-equivalent gets sent to your Gate.io spot account at the current USD/USDT ratio.",
      gateioAmountLabel: "Amount (USD)",
      gateioMaxHint: (max: string) => `up to $${max}`,
      gateioByEmail: "By email",
      gateioByUid: "By UID",
      gateioEmailPlaceholder: "seller@example.com",
      gateioUidPlaceholder: "Gate.io UID",
      submitCancel: "Cancel",
      submitSubmit: "Submit payout",
      submitSubmitting: "Submitting…",
      submitInvalidEmail: "Enter a valid Gate.io email",
      submitInvalidUid: "Enter your Gate.io UID",
      submitSuccess: "Payout submitted",
      submitSuccessDesc: "Gate.io result will land in the payouts table.",
      submitFailed: "Submission failed",
      manualModalTitle: "Other methods",
      manualModalDesc:
        "Creates a payout ticket and locks the balance. An admin wires it by hand.",
      manualAmountLabel: "Amount (USD)",
      manualDetailsLabel: "Payout details",
      manualDetailsPlaceholder: "USDT TRC20 address, name, contact, etc.",
      manualSubmit: "File ticket",
      manualMissingDetails: "Please fill in payout details",
      manualSuccess: "Ticket created",
      manualSuccessDesc: "Balance is locked. An admin will follow up.",
      balanceModalTitle: "Move to API balance",
      balanceModalDesc:
        "This deducts from available provider earnings and credits your wallet balance. It cannot be undone.",
      balanceAmountLabel: "Amount (USD)",
      balanceSubmit: "Confirm move",
      balanceSuccess: "Moved to balance",
      providerTransferModalTitle: "Send to another Provider",
      providerTransferModalDesc:
        "The transfer completes immediately and credits the target owner email's Provider earnings balance. It cannot be undone.",
      providerTransferAmountLabel: "Amount (USD)",
      providerTransferEmailLabel: "Target owner email",
      providerTransferEmailPlaceholder: "provider@example.com",
      providerTransferSubmit: "Confirm transfer",
      providerTransferSuccess: "Sent to Provider",
      internalTransferInvalidAmount: "Enter a valid amount",
      internalTransferInvalidAmountDesc:
        "Amount must be greater than 0 and no more than your available earnings.",
      internalTransferInvalidEmail: "Enter a valid target owner email",
      internalTransferFailed: "Transfer failed",
      payoutMethodGateio: "Gate.io auto payout",
      payoutMethodManual: "Manual payout",
      payoutMethodBalance: "Moved to API balance",
      payoutMethodProvider: "Sent to Provider",
      payoutMethodProviderReceived: "Received from Provider",
      payoutMethodRouterCommission: "Router commission",
      filePickerLabel: "Pick images (PNG / JPG / WebP, ≤ 2 MB)",
      attachmentsTitle: "Image attachments",
      lightboxClose: "Close preview",
      attachmentFallback: "Image",
    },
    support: {
      title: "Support",
      detailTitle: "Ticket detail",
      subtitle:
        "Top-ups, payouts, calls, account issues — all start here. Attachments live in object storage.",
      detailSubtitle: (no: string, hint: string) => `${no} · ${hint}`,
      statusYourTurn: "Your turn",
      statusOurTurn: "Our turn",
      statusEnded: "Closed",
      statusViewing: "Viewing this ticket",
      backToList: "Back to list",
      newTicket: "New ticket",
      anonTitle: "Sign in first",
      anonHint: "Sign in to view, create, and reply to support tickets.",
      openLogin: "Open sign-in",
      view: {
        all: (n: number) => `All ${n}`,
        mine: (n: number) => `Your turn ${n}`,
        platform: (n: number) => `Our turn ${n}`,
        done: (n: number) => `Done ${n}`,
      },
      filterStatusLabel: "Status",
      filterStatusOptions: {
        all: "All",
        open: "Triage",
        waitingAdmin: "On admin",
        waitingUser: "On you",
        resolved: "Resolved",
        closed: "Closed",
      },
      filterPriorityLabel: "Priority",
      priority: {
        all: "All",
        low: "Low",
        normal: "Normal",
        high: "High",
        urgent: "Urgent",
      },
      type: {
        feedback: "Feedback",
        billing_issue: "Money stuff",
        account_issue: "Account / Keys",
        payout_manual: "Manual payout",
      },
      noMatchTitle: "No tickets match",
      noMatchHint: "Try a different status or priority filter.",
      emptySubject: "(no subject)",
      createTitle: "New ticket",
      createDesc: "Image attachments only, ≤ 2 MB each.",
      categoryLabel: "Category",
      category: {
        feedback: "Feedback / bug / request",
        billing: "Top-up / billing / refund",
        account: "Account / API key",
      },
      priorityLabel: "Priority",
      subjectLabel: "Subject",
      subjectPlaceholder: "One line that names the issue",
      bodyLabel: "Details",
      bodyPlaceholder: "Include request id, repro steps, expected vs actual.",
      cancel: "Cancel",
      submit: "Submit",
      submitting: "Submitting…",
      submitMissing: "Please fill in subject and details",
      submitSuccess: "Ticket created",
      submitFailed: "Create failed",
      replyMissing: "Please type a reply",
      replyFailed: "Reply failed",
      closeBtn: "Close ticket",
      closeConfirmTitle: "Close ticket?",
      closeOk: "Confirm close",
      closeFailed: "Close failed",
      closeSuccess: "Ticket closed",
      deleteBtn: "Delete",
      deleteConfirmTitle: "Delete ticket?",
      deleteOk: "Confirm delete",
      deleteFailed: "Delete failed",
      deleteSuccess: "Ticket deleted",
    },
    admin: {
      title: "Admin",
      subtitle:
        "Users, supply, money, tickets and audit — one console. Every write goes to admin_audit.",
      tabs: {
        overview: "Overview",
        users: "Users",
        models: "Models",
        shares: "Shares",
        money: "Money",
        tickets: "Tickets",
        announcements: "News",
        settings: "Settings",
        audit: "Audit",
      },
      ledgerOk: "Ledger balances",
      ledgerBad: "Ledger off",
      ledgerChecking: "Checking",
      overview: {
        todayTopups: "Today: top-ups",
        todayUsage: "Today: spend",
        needsReview: "Needs review",
        pendingPayouts: "Payouts to push",
        openTickets: "Tickets waiting",
        ledger: "Ledger",
        ledgerOk: "Balances",
        ledgerBad: "Off",
      },
      users: {
        emptyTitle: "No users yet",
        colEmail: "Email",
        colStatus: "Status",
        colBalance: "Cash / Locked",
        colCreated: "Joined",
        colActions: "Actions",
        actionAdjust: "Adjust",
        adjustTitle: "Manual adjustment",
        adjustCredit: "+ Credit",
        adjustDebit: "− Debit",
        adjustReasonPlaceholder: "Reason (required, recorded in admin_audit)",
        adjustCancel: "Cancel",
        adjustSubmit: "Confirm",
        adjustReasonMissing: "Reason is required",
        adjustSuccess: "Adjusted",
        adjustFailed: "Adjust failed",
      },
      models: {
        addBtn: "+ Model",
        emptyTitle: "No models configured",
        emptyHint: "Add a model and set its price before users can call it.",
        colType: "Type",
        colPattern: "Model",
        colInput: "Input / 1M",
        colOutput: "Output / 1M",
        colRouting: "Routing",
        colStatus: "Status",
        colActions: "Actions",
        actionEdit: "Edit",
        actionShare: "Routing",
        actionOnline: "Enable",
        actionOffline: "Disable",
        actionDelete: "Delete",
        deleteConfirm: (pattern: string) =>
          `Delete model ${pattern}? Only disabled models can be deleted.`,
        deletedToast: "Model deleted",
        deleteFailed: "Delete failed",
        onlineToast: "Model enabled",
        offlineToast: "Model disabled",
        statusOpFailed: "Operation failed",
        editorTitleNew: "New model",
        editorTitleEdit: "Edit model",
        editorReasonMissing: "Please fill in the price-change reason",
        savedToast: "Model saved",
        saveFailed: "Save failed",
      },
      topups: {
        emptyTitle: "No top-up orders yet",
        colId: "Order",
        colAmount: "Amount",
        colStatus: "Status",
        colTime: "Time",
        colActions: "Actions",
        actionRefund: "Refund",
        refundTitle: "Refund top-up",
        refundOrder: (id: string) => `Order ${id}`,
        refundReasonPlaceholder: "Refund reason",
        refundFeeLabel: "Also refund the top-up fee",
        refundCancel: "Cancel",
        refundSubmit: "Confirm refund",
        refundReasonMissing: "Refund reason is required",
        refundSuccess: "Refund recorded",
      },
      shares: {
        title: "Router shares",
        syncBtn: "Sync now",
        syncOk: "Sync triggered",
        syncFailed: "Sync failed",
        emptyTitle: "No share cache yet",
      },
      money: {
        workspaceTitle: "Money workspace",
        workspaceSubtitle:
          "Top-ups, charges, earnings, payouts, events, ledger — one console. Underlying tables stay independent.",
        tabs: {
          overview: "Summary",
          events: "Events",
          charges: "Charges",
          earnings: "Earnings",
          topups: "Top-ups",
          payouts: "Payouts",
          ledger: "Ledger",
          check: "Checks",
        },
        overview: {
          todayTopups: "Today: top-ups",
          todayUsage: "Today: spend",
          providerPayable: "Provider payable",
          routerPayable: "Router payable",
          payoutReserved: "Payout reserved",
          userCash: "User cash",
          userReserved: "Pre-auth",
          feeRevenue: "Fees / take revenue",
          topupFees: "Top-up fees",
          platformTakeRevenue: "Market take",
          payoutFees: "Payout fees",
          platformCommission: "Platform take",
          marketCommission: "Market",
          routerCommission: "Router",
          riskLoss: "Risk loss",
          pendingTopups: "Pending pay",
          needsReview: "Needs review",
          pendingPayouts: "Pending payouts",
          consistencyTitle: "Ledger consistency",
          consistencyBody: "Account caches must match the ledger aggregate.",
          consistencyOk: "Balances",
          consistencyBad: "Off",
        },
        emptyEvents: "No money events yet",
        emptyCharges: "No charges yet",
        emptyEarnings: "No provider payable summary yet",
        emptyLedger: "Ledger is empty",
        emptyCheck: "No reconciliation results yet",
      },
      payouts: {
        emptyTitle: "No payout requests yet",
        colOwner: "Owner",
        colAmount: "Amount",
        colMethod: "Method",
        colStatus: "Status",
        colExternal: "External tx",
        colActions: "Actions",
        actionExecute: "Run Gate.io",
        actionMarkPaid: "Mark paid",
        actionMarkFailed: "Mark failed",
        actionCancel: "Cancel",
        executeTitle: "Run Gate.io payout",
        executeReasonPlaceholder: "Note (optional)",
        executeConfirm: "Run",
        markFailedTitle: "Mark failed",
        markFailedReasonPlaceholder: "Failure reason",
        markFailedConfirm: "Mark failed",
        cancelTitle: "Cancel payout",
        cancelReasonPlaceholder: "Cancel reason",
        cancelConfirm: "Cancel payout",
        markPaidTitle: "Mark payout completed",
        markPaidExternalPlaceholder: "external tx id",
        markPaidProofPlaceholder: "Proof note",
        markPaidConfirm: "Confirm",
        markPaidExternalMissing: "external tx id is required",
        markPaidProofMissing: "Proof note is required",
        markPaidSuccess: "Marked completed",
        opFailed: "Operation failed",
        opSuccess: "Done",
        opExecuted: "Executed",
        reasonMissing: "Reason is required",
      },
      announcements: {
        addBtn: "+ Post",
        copyJson: "Copy JSON",
        edit: "Edit",
        delete: "Delete",
        emptyTitle: "No announcements",
        manageTitle: "Announcements",
        manageBody:
          "Source of truth is local browser storage. Edits here immediately affect the bell and the announcement modal.",
        copied: "Copied JSON",
        savedNew: "Posted",
        savedEdit: "Updated",
        deleted: "Deleted",
        editorTitleNew: "New announcement",
        editorTitleEdit: "Edit announcement",
        deleteTitle: "Delete announcement",
        deleteConfirmBody: (title: string) => `Delete announcement: ${title}`,
      },
      settings: {
        title: "Settings",
        subtitle: "Manage time zone, environment variables and runtime knobs. Edits write to the .env file on disk.",
        tabs: {
          system: "System",
        },
        categories: {
          runtime: "Runtime",
          auth: "Auth",
          cloudflare: "Cloudflare",
          billing: "Billing",
          routing: "Routing",
          database: "Database",
          storage: "Storage",
          router: "Router",
          payments: "Payments",
        },
        system: {
          timeZoneLabel: "System time zone",
          timeZoneCurrent: "Currently showing",
          timeZoneDefaultSuffix: "default",
          tablePageSizeLabel: "Admin table rows per page",
          tablePageSizeCurrent: (n: number) => `${n} rows per page`,
          tablePageSizeHint: "Applies to every admin table immediately. Range 1-500.",
          tablePageSizeSavedToast: "Table pagination saved",
          savedToast: "Time zone saved",
          saveFailed: "Save failed",
        },
        env: {
          envFileLabel: ".env file",
          hint: "Edits are written to .env; the running market process won't hot-reload — restart to pick them up.",
          unsavedSummary: (n: number) => `${n} unsaved`,
          noUnsaved: "No unsaved changes",
          save: "Save .env",
          reset: "Reset all",
          resetAll: "Reset all changes",
          resetField: "Discard change",
          restoreDefault: "Restore default",
          reveal: "Reveal",
          hide: "Hide",
          copy: "Copy",
          copied: "Copied",
          empty: "empty",
          defaultLabel: "Default",
          required: "Required",
          optional: "Optional",
          modified: "Modified",
          unitSecs: "secs",
          unitDays: "days",
          unitBps: "bps",
          unitUsd: "USD",
          boolOn: "On",
          boolOff: "Off",
          savedToast: ".env saved",
          savedDesc: "Running processes need to restart to pick up the new env values.",
          saveFailed: "Save failed",
          previewTitle: "Review changes",
          previewBody: (n: number) => `${n} change(s) will be written to .env:`,
          previewCancel: "Cancel",
          previewConfirm: "Write changes",
          unchanged: "(unchanged)",
          beforeUnload: "You have unsaved environment changes. Leave anyway?",
        },
        footerLinks: {
          title: "Footer links",
          subtitle: "Items shown in the public footer of every page. Each column packs 3 rows; extras flow into a new column.",
          add: "+ Add link",
          save: "Save footer",
          reset: "Reset all",
          empty: "No footer links yet — click + Add link to start.",
          colIcon: "Icon",
          colLabelZh: "Chinese label",
          colLabelEn: "English label",
          colUrl: "URL",
          colActions: "Actions",
          moveUp: "Move up",
          moveDown: "Move down",
          remove: "Remove",
          urlPlaceholder: "https://example.com",
          labelZhPlaceholder: "e.g. 文档",
          labelEnPlaceholder: "e.g. Docs",
          unsavedSummary: (n: number) => `${n} unsaved`,
          noUnsaved: "No unsaved changes",
          countSummary: (n: number, max: number) => `${n} / ${max} added`,
          limitReached: "Limit reached",
          savedToast: "Footer saved",
          savedDesc: "Public pages reflect the change immediately.",
          saveFailed: "Save failed",
          beforeUnload: "You have unsaved footer changes. Leave anyway?",
          errorMissingLabel: "Provide at least one of Chinese / English label",
          errorMissingUrl: "URL is required",
          errorBadUrl: "URL must start with https://, http://, / or mailto:",
        },
      },
      audit: {
        emptyTitle: "No audit records yet",
      },
    },
  },
} as const;

export type CopyTree = (typeof copy)["zh"];
